services:

  postgres:
    image: postgres:15
    container_name: selftierlist_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_NAME}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - default
  
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    image: selftierlist-fastapi:latest
    container_name: selftierlist_fastapi
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_NAME}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGO=${JWT_ALGO}
      - API_PORT=${API_PORT}
      - URL_PATH_PREFIX=${URL_PATH_PREFIX}
    depends_on:
      - postgres
    networks:
      - default
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: selftierlist-nginx:latest
    container_name: selftierlist-nginx
    ports:
      - 8888:80
    depends_on:
      - fastapi
    networks:
      - default
      - cloudflared_proxy

  adminer:
    image: adminer
    container_name: selftierlist_adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - default